// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soypanxnpkqpipnkxrfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNveXBhbnhucGtxcGlwbmt4cmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTkzMDcsImV4cCI6MjA2ODgzNTMwN30.960SQARa7Yk904s5oXb9_H991TdV03K0lfbDKXMckNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});